version: '3'

services:
  master:
      build:
        context: .
        args:
          MASTER_NODE: master
      image: vitrivr/adampro-dist-hdfs
      entrypoint: "/adampro/bootstrap.sh -d --masternode"
      hostname: master
      environment:
        SPARK_DRIVER_MEMORY: 4g
        SPARK_PUBLIC_DNS: localhost
      expose:
        - 7001
        - 7002
        - 7003
        - 7004
        - 7005
        - 7006
        - 7077
        - 6066
      ports:
        - 2122:2122
        - 4040:4040
        - 6066:6066
        - 7077:7077
        - 8020:8020
        - 8080:8080
        - 8088:8088
        - 9000:9000
        - 9099:9099
        - 19888:19888
        - 50070:50070
      networks:
        - vitrivrnw


  worker:
      build:
        context: .
        args:
          MASTER_NODE: master
      image: vitrivr/adampro-dist-hdfs
      entrypoint: "/adampro/bootstrap.sh -d --workernode"
      environment:
        SPARK_WORKER_CORES: 2
        SPARK_WORKER_MEMORY: 2g
        SPARK_PUBLIC_DNS: localhost
      links:
        - master
      expose:
        - 7012
        - 7013
        - 7014
        - 7015
        - 7016
        - 8881
      ports:
        - 8081
      networks:
        - vitrivrnw

networks:
    vitrivrnw:
      driver: bridge